name: ASCII-ART

on: 
    push

jobs:
    job-1:
      runs-on: ubuntu-latest
      steps:
        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay
          run: cowsay -f dragon "AK THE RED DRAAAAGGGGOOOOONNN" >> dragon.txt

        - name: Upload Dragon File 
          uses: actions/upload-artifact@v4
          with:
            name: dragon-txt-file
            path: dragon.txt

    test-job-2:
        needs: job-1
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon File 
          uses: actions/download-artifact@v3
          with:
            name: dragon-txt-file
        
    test-job-3:
        needs: test-job-2
        runs-on: ubuntu-latest
        steps: 
        - name: Download Dragon File 
          uses: actions/download-artifact@v4
          with:
            name: dragon-txt-file          
          
        - name: CAT
          run: cat dragon.txt


