name: ASCII-ART

on: 
    push

jobs:
    test-job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List Files
              run: ls -la

            - name: Execute Script
              run: |
                chmod +x script.sh
                ./script.sh

    test-job-2:
        runs-on: ubuntu-latest
        steps:
          - name: sleep for 10 seconds
            run: sleep 10
        
    test-job-3:
        runs-on: ubuntu-latest
        steps: 
          - name: CAT
            run: cat dragon.txt


