name: ASCII-ART

on: 
    push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List Files
              run: ls -la

            - name: Execute Script
              run: |
                chmod +x script.sh
                ./script.sh

