name: ASCII-ART

on: 
    push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Execute Script
              uses: ./script.sh

            - name: List Files
              run: ls -la

