name: ASCII-ART

on: 
    push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Cowsay
              run: sudo apt-get install cowsay -y

            - name: Run Cowsay
              run: cowsay -f dragon "Draa Draa Dragoonnn" >> dragon.txt

            - name: Test File
              run: grep -i "dra" dragon.txt
              
            - name: Read File
              run: cat dragon.txt

            - name: List Files
              run: ls -la

